[workspace]
members = [
    "sample",
    "leetnotes",
]
exclude = [
	"skynet",
	"serrana",
	"serrana-beta",
	"serrana-poise",
  "yew-app"
]


[workspace.package]
version = "0.0.1"
authors = ["OverzealousLotus"]
description = "Projects for Rust."
license = "GPL-3.0"


[profile.dev]
strip = true
opt-level = 2
incremental = true
lto = false
